package com.thd.note.pojo;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.annotations.GenericGenerator;

/**
 * cn.thd.pojo.se.Note entity. file autogenerated by ThirdteenDevils's
 * CodeGenUtil
 */

@Entity
@Table(name = "note")
public class Note implements Serializable {

	@Id
	@GeneratedValue(generator = "uuid.hex")
	@GenericGenerator(name = "uuid.hex", strategy = "uuid.hex")
	@Column(name = "id")
	private java.lang.String id;

	//
	@Column(name = "title")
	private java.lang.String title;
	//
	@Column(name = "content")
	private java.lang.String content;
	//
	@Column(name = "create_date")
	private java.util.Date createDate;

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setContent(java.lang.String content) {
		this.content = content;
	}

	public java.lang.String getContent() {
		return this.content;
	}

	public java.util.Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(java.util.Date createDate) {
		this.createDate = createDate;
	}

}
